services:
  star-office-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: star-office-ui
    restart: unless-stopped
    ports:
      - "19000:19000"
      - "32821:80"
    environment:
      - ASSET_DRAWER_PASS=438516720
      - FLASK_SECRET_KEY=changeme